In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

BASE_DIR = "/content/drive/MyDrive/AI_Email_Deliverability_Intelligence"

folders = [
    "data/raw",
    "data/processed",
    "data/external",
    "notebooks",
    "models",
    "src",
    "reports"
]

for folder in folders:
    os.makedirs(os.path.join(BASE_DIR, folder), exist_ok=True)

print("Project folders created successfully.")

Project folders created successfully.

In [ ]:
import requests
from tqdm.auto import tqdm

url = "https://zenodo.org/records/17985618/files/SendGuard900K.csv?download=1"

output_path = os.path.join(
    BASE_DIR,
    "data",
    "raw",
    "SendGuard900K.csv"
)

response = requests.get(url, stream=True)
response.raise_for_status()

total_size = int(response.headers.get("content-length", 0))

with open(output_path, "wb") as file, tqdm(
    total=total_size,
    unit="B",
    unit_scale=True,
    desc="Downloading SendGuard900K"
) as progress:

    for chunk in response.iter_content(chunk_size=1024 * 1024):
        if chunk:
            file.write(chunk)
            progress.update(len(chunk))

print("\nDownload completed.")
print("Saved at:", output_path)

Downloading SendGuard900K: 0.00B [00:00, ?B/s]

Download completed.
Saved at: /content/drive/MyDrive/AI_Email_Deliverability_Intelligence/data/raw/SendGuard900K.csv

In [ ]:
import os

print("File exists:", os.path.exists(output_path))
print("File size (MB):", round(os.path.getsize(output_path) / (1024**2), 2))

File exists: True
File size (MB): 307.27

In [ ]:
import pandas as pd

df = pd.read_csv(output_path, nrows=10)

print("Sample shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

df.head()

Sample shape: (10, 119)

Columns:
['client_id', 'client_tag_name', 'client_tag_num', 'campaign_id', 'campaign_test_id', 'campaign_test_part', 'campaign_test_type', 'campaign_sent_time', 'message_content_size', 'message_images_count', 'message_embedded_images_count', 'message_embedded_images_size', 'message_embedded_files_count', 'message_embedded_files_size', 'message_links_count', 'message_links_blocked_count', 'message_personalization_tags_count', 'message_personalization_tags_in_sender_email_count', 'message_personalization_tags_in_subject_count', 'message_personalization_tags_in_html_body_count', 'message_personalization_tags_in_text_body_count', 'custom_fields_used_in_campaign', 'campaign_subscribers_count', 'campaign_phantom_bounce_count', 'campaign_subscribers_blocked_count', 'campaign_opens_count', 'campaign_unique_opens_count', 'campaign_clicks_count', 'campaign_unique_clicks_count', 'campaign_soft_bounced_count', 'campaign_hard_bounced_count', 'campaign_resigned_count', 'campaign_complaint_count', 'campaign_phishing_count', 'campaign_moderation_rejected_count', 'campaign_moderation', 'campaign_landing_page', 'campaign_opens_count_0', 'campaign_unique_opens_count_0', 'campaign_clicks_count_0', 'campaign_unique_clicks_count_0', 'campaign_soft_bounced_count_0', 'campaign_hard_bounced_count_0', 'campaign_resigned_count_0', 'campaign_complaint_count_0', 'campaign_opens_count_30', 'campaign_unique_opens_count_30', 'campaign_clicks_count_30', 'campaign_unique_clicks_count_30', 'campaign_soft_bounced_count_30', 'campaign_hard_bounced_count_30', 'campaign_resigned_count_30', 'campaign_complaint_count_30', 'campaign_opens_count_60', 'campaign_unique_opens_count_60', 'campaign_clicks_count_60', 'campaign_unique_clicks_count_60', 'campaign_soft_bounced_count_60', 'campaign_hard_bounced_count_60', 'campaign_resigned_count_60', 'campaign_complaint_count_60', 'campaign_opens_count_180', 'campaign_unique_opens_count_180', 'campaign_clicks_count_180', 'campaign_unique_clicks_count_180', 'campaign_soft_bounced_count_180', 'campaign_hard_bounced_count_180', 'campaign_resigned_count_180', 'campaign_complaint_count_180', 'campaign_opens_count_360', 'campaign_unique_opens_count_360', 'campaign_clicks_count_360', 'campaign_unique_clicks_count_360', 'campaign_soft_bounced_count_360', 'campaign_hard_bounced_count_360', 'campaign_resigned_count_360', 'campaign_complaint_count_360', 'campaign_opens_count_720', 'campaign_unique_opens_count_720', 'campaign_clicks_count_720', 'campaign_unique_clicks_count_720', 'campaign_soft_bounced_count_720', 'campaign_hard_bounced_count_720', 'campaign_resigned_count_720', 'campaign_complaint_count_720', 'campaign_opens_count_1440', 'campaign_unique_opens_count_1440', 'campaign_clicks_count_1440', 'campaign_unique_clicks_count_1440', 'campaign_soft_bounced_count_1440', 'campaign_hard_bounced_count_1440', 'campaign_resigned_count_1440', 'campaign_complaint_count_1440', 'campaign_opens_count_2880', 'campaign_unique_opens_count_2880', 'campaign_clicks_count_2880', 'campaign_unique_clicks_count_2880', 'campaign_soft_bounced_count_2880', 'campaign_hard_bounced_count_2880', 'campaign_resigned_count_2880', 'campaign_complaint_count_2880', 'campaign_opens_count_4320', 'campaign_unique_opens_count_4320', 'campaign_clicks_count_4320', 'campaign_unique_clicks_count_4320', 'campaign_soft_bounced_count_4320', 'campaign_hard_bounced_count_4320', 'campaign_resigned_count_4320', 'campaign_complaint_count_4320', 'domain_in_links_min_creation_time', 'domain_in_links_max_creation_time', 'domain_in_links_avg_creation_time', 'domain_in_links_most_used_creation_time', 'domain_in_links_min_creation_time_diff', 'domain_in_links_max_creation_time_diff', 'domain_in_links_avg_creation_time_diff', 'domain_in_links_most_used_creation_time_diff', 'registrar_domain_number', 'domain_number']

,client_id,client_tag_name,client_tag_num,campaign_id,campaign_test_id,campaign_test_part,campaign_test_type,campaign_sent_time,message_content_size,message_images_count,...,domain_in_links_min_creation_time,domain_in_links_max_creation_time,domain_in_links_avg_creation_time,domain_in_links_most_used_creation_time,domain_in_links_min_creation_time_diff,domain_in_links_max_creation_time_diff,domain_in_links_avg_creation_time_diff,domain_in_links_most_used_creation_time_diff,registrar_domain_number,domain_number
0,171728,NaN,0,5995662,90351,part,sender_name,2024-04-01T03:00:07+01:00,40968,10,...,2004-06-04,2004-06-04,2004-06-04,NaN,7241,7241,7241,-1,2,2
1,147025,NaN,0,5994558,0,0,0,2024-04-01T03:00:08+01:00,11330,5,...,2016-09-27,2016-09-27,2016-09-27,2016-09-27,2743,2743,2743,2743,1,1
2,171728,NaN,0,5995663,90351,part,sender_name,2024-04-01T03:00:08+01:00,40968,10,...,2004-06-04,2004-06-04,2004-06-04,NaN,7241,7241,7241,-1,2,2
3,463419,NaN,0,5995628,0,0,0,2024-04-01T03:00:40+01:00,81182,21,...,1997-03-29,2005-02-15,2001-09-22,2002-10-25,9865,6985,8227,7829,5,5
4,503371,NaN,0,5995646,0,0,0,2024-04-01T04:00:06+01:00,52177,4,...,2001-04-07,2001-04-07,2001-04-07,2001-04-07,8395,8395,8395,8395,3,3

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Columns: 119 entries, client_id to domain_number
dtypes: int64(111), object(8)
memory usage: 9.4+ KB

In [ ]:
print(df.columns.tolist())

['client_id', 'client_tag_name', 'client_tag_num', 'campaign_id', 'campaign_test_id', 'campaign_test_part', 'campaign_test_type', 'campaign_sent_time', 'message_content_size', 'message_images_count', 'message_embedded_images_count', 'message_embedded_images_size', 'message_embedded_files_count', 'message_embedded_files_size', 'message_links_count', 'message_links_blocked_count', 'message_personalization_tags_count', 'message_personalization_tags_in_sender_email_count', 'message_personalization_tags_in_subject_count', 'message_personalization_tags_in_html_body_count', 'message_personalization_tags_in_text_body_count', 'custom_fields_used_in_campaign', 'campaign_subscribers_count', 'campaign_phantom_bounce_count', 'campaign_subscribers_blocked_count', 'campaign_opens_count', 'campaign_unique_opens_count', 'campaign_clicks_count', 'campaign_unique_clicks_count', 'campaign_soft_bounced_count', 'campaign_hard_bounced_count', 'campaign_resigned_count', 'campaign_complaint_count', 'campaign_phishing_count', 'campaign_moderation_rejected_count', 'campaign_moderation', 'campaign_landing_page', 'campaign_opens_count_0', 'campaign_unique_opens_count_0', 'campaign_clicks_count_0', 'campaign_unique_clicks_count_0', 'campaign_soft_bounced_count_0', 'campaign_hard_bounced_count_0', 'campaign_resigned_count_0', 'campaign_complaint_count_0', 'campaign_opens_count_30', 'campaign_unique_opens_count_30', 'campaign_clicks_count_30', 'campaign_unique_clicks_count_30', 'campaign_soft_bounced_count_30', 'campaign_hard_bounced_count_30', 'campaign_resigned_count_30', 'campaign_complaint_count_30', 'campaign_opens_count_60', 'campaign_unique_opens_count_60', 'campaign_clicks_count_60', 'campaign_unique_clicks_count_60', 'campaign_soft_bounced_count_60', 'campaign_hard_bounced_count_60', 'campaign_resigned_count_60', 'campaign_complaint_count_60', 'campaign_opens_count_180', 'campaign_unique_opens_count_180', 'campaign_clicks_count_180', 'campaign_unique_clicks_count_180', 'campaign_soft_bounced_count_180', 'campaign_hard_bounced_count_180', 'campaign_resigned_count_180', 'campaign_complaint_count_180', 'campaign_opens_count_360', 'campaign_unique_opens_count_360', 'campaign_clicks_count_360', 'campaign_unique_clicks_count_360', 'campaign_soft_bounced_count_360', 'campaign_hard_bounced_count_360', 'campaign_resigned_count_360', 'campaign_complaint_count_360', 'campaign_opens_count_720', 'campaign_unique_opens_count_720', 'campaign_clicks_count_720', 'campaign_unique_clicks_count_720', 'campaign_soft_bounced_count_720', 'campaign_hard_bounced_count_720', 'campaign_resigned_count_720', 'campaign_complaint_count_720', 'campaign_opens_count_1440', 'campaign_unique_opens_count_1440', 'campaign_clicks_count_1440', 'campaign_unique_clicks_count_1440', 'campaign_soft_bounced_count_1440', 'campaign_hard_bounced_count_1440', 'campaign_resigned_count_1440', 'campaign_complaint_count_1440', 'campaign_opens_count_2880', 'campaign_unique_opens_count_2880', 'campaign_clicks_count_2880', 'campaign_unique_clicks_count_2880', 'campaign_soft_bounced_count_2880', 'campaign_hard_bounced_count_2880', 'campaign_resigned_count_2880', 'campaign_complaint_count_2880', 'campaign_opens_count_4320', 'campaign_unique_opens_count_4320', 'campaign_clicks_count_4320', 'campaign_unique_clicks_count_4320', 'campaign_soft_bounced_count_4320', 'campaign_hard_bounced_count_4320', 'campaign_resigned_count_4320', 'campaign_complaint_count_4320', 'domain_in_links_min_creation_time', 'domain_in_links_max_creation_time', 'domain_in_links_avg_creation_time', 'domain_in_links_most_used_creation_time', 'domain_in_links_min_creation_time_diff', 'domain_in_links_max_creation_time_diff', 'domain_in_links_avg_creation_time_diff', 'domain_in_links_most_used_creation_time_diff', 'registrar_domain_number', 'domain_number']

In [ ]:
print(df[['client_id', 'campaign_id', 'client_tag_name',
          'domain_number', 'registrar_domain_number']].head(10))

   client_id  campaign_id client_tag_name  domain_number  \
0     171728      5995662             NaN              2
1     147025      5994558             NaN              1
2     171728      5995663             NaN              2
3     463419      5995628             NaN              5
4     503371      5995646             NaN              3
5     481573      5993861             NaN              3
6     525231      5987876             NaN              1
7      44833      5994425             NaN              5
8     510395      5987692       Chwilówka              1
9     480559      5992378             NaN              2

   registrar_domain_number
0                        2
1                        1
2                        2
3                        5
4                        3
5                        3
6                        1
7                        5
8                        1
9                        2

In [ ]:
print(df[['client_id', 'client_tag_name', 'client_tag_num']].drop_duplicates().head(20))

   client_id client_tag_name  client_tag_num
0     171728             NaN               0
1     147025             NaN               0
3     463419             NaN               0
4     503371             NaN               0
5     481573             NaN               0
6     525231             NaN               0
7      44833             NaN               0
8     510395       Chwilówka               2
9     480559             NaN               0

In [ ]:
print("Unique clients:", df['client_id'].nunique())
print("Unique campaigns:", df['campaign_id'].nunique())
print("Unique client tags:", df['client_tag_name'].nunique(dropna=True))

Unique clients: 9
Unique campaigns: 10
Unique client tags: 1

In [ ]:
import pandas as pd
import os

file_path = "/content/drive/MyDrive/AI_Email_Deliverability_Intelligence/data/raw/SendGuard900K.csv"

unique_clients = set()
unique_campaigns = set()
unique_tags = set()

total_rows = 0

for chunk in pd.read_csv(file_path, chunksize=50000):

    total_rows += len(chunk)

    unique_clients.update(chunk["client_id"].dropna().unique())
    unique_campaigns.update(chunk["campaign_id"].dropna().unique())
    unique_tags.update(chunk["client_tag_name"].dropna().unique())

print("Total rows:", total_rows)
print("Unique clients:", len(unique_clients))
print("Unique campaigns:", len(unique_campaigns))
print("Unique client tags:", len(unique_tags))

Total rows: 908229
Unique clients: 4112
Unique campaigns: 908226
Unique client tags: 3

/tmp/ipykernel_2860/877793955.py:12: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=50000):

In [ ]:
import pandas as pd

dates = pd.read_csv(
    file_path,
    usecols=["campaign_sent_time"],
    parse_dates=["campaign_sent_time"]
)

print("Earliest campaign:", dates["campaign_sent_time"].min())
print("Latest campaign:", dates["campaign_sent_time"].max())

Earliest campaign: 2022-01-01T05:00:05Z
Latest campaign: 2024-12-31T23:10:08Z

In [ ]:
df_check = pd.read_csv(file_path, nrows=10000)

important_columns = [
    "campaign_subscribers_count",
    "campaign_opens_count",
    "campaign_unique_opens_count",
    "campaign_clicks_count",
    "campaign_unique_clicks_count",
    "campaign_soft_bounced_count",
    "campaign_hard_bounced_count",
    "campaign_complaint_count",
    "campaign_phishing_count",
    "campaign_moderation"
]

print(df_check[important_columns].isnull().sum())

campaign_subscribers_count      0
campaign_opens_count            0
campaign_unique_opens_count     0
campaign_clicks_count           0
campaign_unique_clicks_count    0
campaign_soft_bounced_count     0
campaign_hard_bounced_count     0
campaign_complaint_count        0
campaign_phishing_count         0
campaign_moderation             0
dtype: int64

In [ ]:
import pandas as pd

file_path = "/content/drive/MyDrive/AI_Email_Deliverability_Intelligence/data/raw/SendGuard900K.csv"

missing_counts = pd.Series(dtype="int64")

for chunk in pd.read_csv(
    file_path,
    chunksize=50000,
    low_memory=False
):
    chunk_missing = chunk.isnull().sum()

    if missing_counts.empty:
        missing_counts = chunk_missing
    else:
        missing_counts = missing_counts.add(chunk_missing, fill_value=0)

missing_counts = missing_counts.astype(int)

missing_summary = (
    missing_counts
    .sort_values(ascending=False)
    .to_frame("missing_count")
)

missing_summary["missing_percentage"] = (
    missing_summary["missing_count"] / 908229 * 100
)

missing_summary.head(30)

,missing_count,missing_percentage
client_tag_name,606654,66.795269
domain_in_links_most_used_creation_time,437221,48.139951
domain_in_links_avg_creation_time,182273,20.069057
domain_in_links_min_creation_time,182273,20.069057
domain_in_links_max_creation_time,182273,20.069057
client_id,0,0.000000
client_tag_num,0,0.000000
campaign_sent_time,0,0.000000
message_content_size,0,0.000000
message_images_count,0,0.000000
message_embedded_images_count,0,0.000000
message_embedded_images_size,0,0.000000
message_embedded_files_count,0,0.000000
message_embedded_files_size,0,0.000000
message_links_count,0,0.000000
message_links_blocked_count,0,0.000000
message_personalization_tags_count,0,0.000000
message_personalization_tags_in_sender_email_count,0,0.000000
message_personalization_tags_in_subject_count,0,0.000000
campaign_id,0,0.000000
campaign_test_id,0,0.000000
campaign_test_part,0,0.000000
campaign_test_type,0,0.000000
campaign_phantom_bounce_count,0,0.000000
campaign_subscribers_blocked_count,0,0.000000
campaign_opens_count,0,0.000000
campaign_unique_opens_count,0,0.000000
campaign_clicks_count,0,0.000000
campaign_unique_clicks_count,0,0.000000
campaign_soft_bounced_count,0,0.000000

In [ ]:
duplicate_campaigns = []

for chunk in pd.read_csv(
    file_path,
    usecols=["campaign_id"],
    chunksize=50000,
    low_memory=False
):
    duplicate_campaigns.append(chunk)

campaign_ids = pd.concat(duplicate_campaigns, ignore_index=True)

print("Total campaign records:", len(campaign_ids))
print("Unique campaign IDs:", campaign_ids["campaign_id"].nunique())
print("Duplicate campaign rows:",
      campaign_ids["campaign_id"].duplicated().sum())

Total campaign records: 908229
Unique campaign IDs: 908226
Duplicate campaign rows: 3

In [ ]:
print(
    campaign_ids[
        campaign_ids["campaign_id"].duplicated(keep=False)
    ].sort_values("campaign_id")
)

       campaign_id
79332      4896232
79333      4896232
79334      4896232
79335      4896232

In [ ]:
test_columns = [
    "campaign_test_part",
    "campaign_test_type"
]

test_data = pd.read_csv(
    file_path,
    usecols=test_columns,
    low_memory=False
)

for col in test_columns:
    print("\n", "="*50)
    print(col)
    print(test_data[col].value_counts(dropna=False).head(30))
    print("dtype:", test_data[col].dtype)

 ==================================================
campaign_test_part
campaign_test_part
0        886470
part      16013
final      5746
Name: count, dtype: int64
dtype: object

 ==================================================
campaign_test_type
campaign_test_type
0              886470
sender_name     16944
optimizer        4527
topic             288
Name: count, dtype: int64
dtype: object

In [ ]:
test_analysis = pd.read_csv(
    file_path,
    usecols=[
        "campaign_id",
        "client_id",
        "campaign_test_part",
        "campaign_test_type"
    ],
    low_memory=False
)

duplicate_campaigns = test_analysis[
    test_analysis["campaign_id"].duplicated(keep=False)
].sort_values("campaign_id")

print(duplicate_campaigns.to_string(index=False))

 client_id  campaign_id campaign_test_part campaign_test_type
     40849      4896232                  0                  0
     40849      4896232                  0                  0
     40849      4896232                  0                  0
     40849      4896232                  0                  0

In [ ]:
print(
    test_analysis["campaign_test_type"]
    .value_counts(dropna=False)
)

campaign_test_type
0              886470
sender_name     16944
optimizer        4527
topic             288
Name: count, dtype: int64

In [ ]:
print(
    pd.crosstab(
        test_analysis["campaign_test_part"],
        test_analysis["campaign_test_type"],
        dropna=False
    )
)

campaign_test_type       0  optimizer  sender_name  topic
campaign_test_part
0                   886470          0            0      0
final                    0          4         5646     96
part                     0       4523        11298    192

In [ ]:
full_check = pd.read_csv(
    file_path,
    low_memory=False
)

print("Total rows:", len(full_check))
print("Exact duplicate rows:", full_check.duplicated().sum())

Total rows: 908229
Exact duplicate rows: 3

In [ ]:
exact_duplicates = full_check[
    full_check.duplicated(keep=False)
]

print("Rows involved in exact duplicates:", len(exact_duplicates))

Rows involved in exact duplicates: 4

In [ ]:
print(
    full_check[
        full_check["campaign_id"] == 4896232
    ].to_string(index=False)
)

 client_id client_tag_name  client_tag_num  campaign_id  campaign_test_id campaign_test_part campaign_test_type   campaign_sent_time  message_content_size  message_images_count  message_embedded_images_count  message_embedded_images_size  message_embedded_files_count  message_embedded_files_size  message_links_count  message_links_blocked_count  message_personalization_tags_count  message_personalization_tags_in_sender_email_count  message_personalization_tags_in_subject_count  message_personalization_tags_in_html_body_count  message_personalization_tags_in_text_body_count  custom_fields_used_in_campaign  campaign_subscribers_count  campaign_phantom_bounce_count  campaign_subscribers_blocked_count  campaign_opens_count  campaign_unique_opens_count  campaign_clicks_count  campaign_unique_clicks_count  campaign_soft_bounced_count  campaign_hard_bounced_count  campaign_resigned_count  campaign_complaint_count  campaign_phishing_count  campaign_moderation_rejected_count  campaign_moderation  campaign_landing_page  campaign_opens_count_0  campaign_unique_opens_count_0  campaign_clicks_count_0  campaign_unique_clicks_count_0  campaign_soft_bounced_count_0  campaign_hard_bounced_count_0  campaign_resigned_count_0  campaign_complaint_count_0  campaign_opens_count_30  campaign_unique_opens_count_30  campaign_clicks_count_30  campaign_unique_clicks_count_30  campaign_soft_bounced_count_30  campaign_hard_bounced_count_30  campaign_resigned_count_30  campaign_complaint_count_30  campaign_opens_count_60  campaign_unique_opens_count_60  campaign_clicks_count_60  campaign_unique_clicks_count_60  campaign_soft_bounced_count_60  campaign_hard_bounced_count_60  campaign_resigned_count_60  campaign_complaint_count_60  campaign_opens_count_180  campaign_unique_opens_count_180  campaign_clicks_count_180  campaign_unique_clicks_count_180  campaign_soft_bounced_count_180  campaign_hard_bounced_count_180  campaign_resigned_count_180  campaign_complaint_count_180  campaign_opens_count_360  campaign_unique_opens_count_360  campaign_clicks_count_360  campaign_unique_clicks_count_360  campaign_soft_bounced_count_360  campaign_hard_bounced_count_360  campaign_resigned_count_360  campaign_complaint_count_360  campaign_opens_count_720  campaign_unique_opens_count_720  campaign_clicks_count_720  campaign_unique_clicks_count_720  campaign_soft_bounced_count_720  campaign_hard_bounced_count_720  campaign_resigned_count_720  campaign_complaint_count_720  campaign_opens_count_1440  campaign_unique_opens_count_1440  campaign_clicks_count_1440  campaign_unique_clicks_count_1440  campaign_soft_bounced_count_1440  campaign_hard_bounced_count_1440  campaign_resigned_count_1440  campaign_complaint_count_1440  campaign_opens_count_2880  campaign_unique_opens_count_2880  campaign_clicks_count_2880  campaign_unique_clicks_count_2880  campaign_soft_bounced_count_2880  campaign_hard_bounced_count_2880  campaign_resigned_count_2880  campaign_complaint_count_2880  campaign_opens_count_4320  campaign_unique_opens_count_4320  campaign_clicks_count_4320  campaign_unique_clicks_count_4320  campaign_soft_bounced_count_4320  campaign_hard_bounced_count_4320  campaign_resigned_count_4320  campaign_complaint_count_4320 domain_in_links_min_creation_time domain_in_links_max_creation_time domain_in_links_avg_creation_time domain_in_links_most_used_creation_time  domain_in_links_min_creation_time_diff  domain_in_links_max_creation_time_diff  domain_in_links_avg_creation_time_diff  domain_in_links_most_used_creation_time_diff  registrar_domain_number  domain_number
     40849             NaN               0      4896232                 0                  0                  0 2022-01-31T11:00:13Z                 59947                    18                              0                             0                             0                            0                   20                            0                                   0                                                   0                                              0                                                0                                                0                               0                        2102                              0                                   0                   214                          175                     26                            21                            2                            0                        0                         0                        0                                   0                    1                      0                       5                              4                        0                               0                              0                              0                          0                           0                       42                              40                         5                                5                               1                               0                           0                            0                       58                              54                         6                                6                               1                               0                           0                            0                       102                               92                         11                                11                                1                                0                            0                             0                       124                              110                         12                                12                                1                                0                            0                             0                       163                              139                         20                                18                                1                                0                            0                             0                        188                               158                          21                                 19                                 1                                 0                             0                              0                        207                               171                          26                                 21                                 2                                 0                             0                              0                        214                               175                          26                                 21                                 2                                 0                             0                              0                        1997-03-29                        2012-10-12                        2004-11-30                              2012-10-12                                    9074                                    3398                                    6271                                          3398                        4              4
     40849             NaN               0      4896232                 0                  0                  0 2022-01-31T11:00:13Z                 59947                    18                              0                             0                             0                            0                   20                            0                                   0                                                   0                                              0                                                0                                                0                               0                        2102                              0                                   0                   214                          175                     26                            21                            2                            0                        0                         0                        0                                   0                    1                      0                       5                              4                        0                               0                              0                              0                          0                           0                       42                              40                         5                                5                               1                               0                           0                            0                       58                              54                         6                                6                               1                               0                           0                            0                       102                               92                         11                                11                                1                                0                            0                             0                       124                              110                         12                                12                                1                                0                            0                             0                       163                              139                         20                                18                                1                                0                            0                             0                        188                               158                          21                                 19                                 1                                 0                             0                              0                        207                               171                          26                                 21                                 2                                 0                             0                              0                        214                               175                          26                                 21                                 2                                 0                             0                              0                        1997-03-29                        2012-10-12                        2004-11-30                              2012-10-12                                    9074                                    3398                                    6271                                          3398                        4              4
     40849             NaN               0      4896232                 0                  0                  0 2022-01-31T11:00:13Z                 59947                    18                              0                             0                             0                            0                   20                            0                                   0                                                   0                                              0                                                0                                                0                               0                        2102                              0                                   0                   214                          175                     26                            21                            2                            0                        0                         0                        0                                   0                    1                      0                       5                              4                        0                               0                              0                              0                          0                           0                       42                              40                         5                                5                               1                               0                           0                            0                       58                              54                         6                                6                               1                               0                           0                            0                       102                               92                         11                                11                                1                                0                            0                             0                       124                              110                         12                                12                                1                                0                            0                             0                       163                              139                         20                                18                                1                                0                            0                             0                        188                               158                          21                                 19                                 1                                 0                             0                              0                        207                               171                          26                                 21                                 2                                 0                             0                              0                        214                               175                          26                                 21                                 2                                 0                             0                              0                        1997-03-29                        2012-10-12                        2004-11-30                              2012-10-12                                    9074                                    3398                                    6271                                          3398                        4              4
     40849             NaN               0      4896232                 0                  0                  0 2022-01-31T11:00:13Z                 59947                    18                              0                             0                             0                            0                   20                            0                                   0                                                   0                                              0                                                0                                                0                               0                        2102                              0                                   0                   214                          175                     26                            21                            2                            0                        0                         0                        0                                   0                    1                      0                       5                              4                        0                               0                              0                              0                          0                           0                       42                              40                         5                                5                               1                               0                           0                            0                       58                              54                         6                                6                               1                               0                           0                            0                       102                               92                         11                                11                                1                                0                            0                             0                       124                              110                         12                                12                                1                                0                            0                             0                       163                              139                         20                                18                                1                                0                            0                             0                        188                               158                          21                                 19                                 1                                 0                             0                              0                        207                               171                          26                                 21                                 2                                 0                             0                              0                        214                               175                          26                                 21                                 2                                 0                             0                              0                        1997-03-29                        2012-10-12                        2004-11-30                              2012-10-12                                    9074                                    3398                                    6271                                          3398                        4              4

In [ ]:
categorical_columns = [
    "client_tag_name",
    "campaign_test_part",
    "campaign_test_type",
    "campaign_moderation",
    "campaign_landing_page"
]

cat_data = pd.read_csv(
    file_path,
    usecols=categorical_columns,
    low_memory=False
)

for col in categorical_columns:
    print("\n" + "=" * 60)
    print(col)
    print(cat_data[col].value_counts(dropna=False))

============================================================
client_tag_name
client_tag_name
NaN            606654
Inne           280085
Chwilówka       12012
Dom mediowy      9478
Name: count, dtype: int64

============================================================
campaign_test_part
campaign_test_part
0        886470
part      16013
final      5746
Name: count, dtype: int64

============================================================
campaign_test_type
campaign_test_type
0              886470
sender_name     16944
optimizer        4527
topic             288
Name: count, dtype: int64

============================================================
campaign_moderation
campaign_moderation
0    465283
1    442946
Name: count, dtype: int64

============================================================
campaign_landing_page
campaign_landing_page
0    907857
1       372
Name: count, dtype: int64